[deploy]
startCommand = "php artisan config:cache && php artisan route:cache && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
RAILPACK_PHP_VERSION = "8.4"
